# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LicenseTool < Formula
  desc "Audit and standardize license headers and metadata across codebases"
  homepage "https://github.com/KofTwentyTwo/license-tool"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.1.1/license-tool_0.1.1_darwin_amd64.tar.gz"
      sha256 "fedfa149d0912437c5474796f12aa32327b4cb605bc93360eb7bfd1f94c0ee29"

      define_method(:install) do
        bin.install "license-tool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.1.1/license-tool_0.1.1_darwin_arm64.tar.gz"
      sha256 "4bd90eac0d3fb857d1b05ac5b2f1cd3d0b9b0d7429e004873a583c8922feb698"

      define_method(:install) do
        bin.install "license-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.1.1/license-tool_0.1.1_linux_amd64.tar.gz"
      sha256 "1a5877e6d721ad3355e4bb4c96bd9f6c6e669baa509741eada5cf1ee44b899a2"
      define_method(:install) do
        bin.install "license-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.1.1/license-tool_0.1.1_linux_arm64.tar.gz"
      sha256 "08211a135549ee6114939c70cd4f6b890d3edc672e37ab1b8165cabc9a516c6b"
      define_method(:install) do
        bin.install "license-tool"
      end
    end
  end

  test do
    system "#{bin}/license-tool", "version"
  end
end
