# This file was generated by GoReleaser. DO NOT EDIT.
cask "license-tool" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ddb5a70d0964a086a2488d98b0b03305ef25dd360cc9985266e86f819bfccf7a"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66af3b8a6c0eaf6ca30f2df497522775dbb451106244bcf79b015896db618ae2"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "47c2e0692827ceed0bdc11f2cd6a0a7f52f8dbab7ee4730b5319e508e9d98650"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de2380cfe1f46dc69986afc66c0af5ffbe630fa926e134372dac34361daa3165"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "license-tool"
  desc "Audit and standardize license headers and metadata across codebases"
  homepage "https://github.com/KofTwentyTwo/license-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "license-tool"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/license-tool"]
    end
  end

  # No zap stanza required

end
