# This file was generated by GoReleaser. DO NOT EDIT.
cask "license-tool" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "24321e7746aea37970e1ecef5609e6894345e403f3b937e80622b3f39a9bdfc4"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "22c6f1df48408225e1db253bc3d3e84743e0ae0cb6051244ea8c2ee7d1479c78"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "755e22bf67ce5f76d7eabb97b2c5566efa4410a8222ce25bb927f28e6a966c3d"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "773409ee85ce49af1a0b1b4b1dccb1f5f6476bcd7a951c2eb3ecef0072cfa85a"
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v#{version}/license-tool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "license-tool"
  desc "Audit and standardize license headers and metadata across codebases"
  homepage "https://github.com/KofTwentyTwo/license-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "license-tool"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/license-tool"]
    end
  end

  # No zap stanza required

end
