# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LicenseTool < Formula
  desc "Audit and standardize license headers and metadata across codebases"
  homepage "https://github.com/KofTwentyTwo/license-tool"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.2.1/license-tool_0.2.1_darwin_amd64.tar.gz"
      sha256 "d3954e5807414f67b8860c62d6732daaa838276cb6c12582c0b364df7657694f"

      define_method(:install) do
        bin.install "license-tool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.2.1/license-tool_0.2.1_darwin_arm64.tar.gz"
      sha256 "f8b2fe0abe465c6199b921f1c4efd59b67944e71d8371358953ea3cb87a1fd24"

      define_method(:install) do
        bin.install "license-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.2.1/license-tool_0.2.1_linux_amd64.tar.gz"
      sha256 "a722d76d20073c819a871a6d31d195ec811b0fc2cf717dd92d845255efe11734"
      define_method(:install) do
        bin.install "license-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KofTwentyTwo/license-tool/releases/download/v0.2.1/license-tool_0.2.1_linux_arm64.tar.gz"
      sha256 "5fa36cb22ae85dd868bcce156726cc17fcd3b233e0e7b7db61df01b853e2899f"
      define_method(:install) do
        bin.install "license-tool"
      end
    end
  end

  test do
    system "#{bin}/license-tool", "version"
  end
end
